- name: Install nginx on servers
  hosts: servers
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: true
        cache_valid_time: 3600
    - name: Nginx service configuration
      service:
        name: nginx
        state: started
        enabled: true
    - name: Sample HTML file template
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.nginx-debian.html
        owner: www-data
        group: www-data
        mode: '0644'
      notify: Reload Nginx
  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
